feat: change token & refresh list exercices' list
pfitaxel/learn-ocaml.el pull request #19
Opened 2021-05-26 09:11 UTC by LouisAyroles

- update learn-ocaml-change-server in order to be able to change our token right after changing server
- suggest that change server -> refresh exercises' list

2021-05-26 10:10 UTC, erikmd commented
Closing and reopening the PR to restart Travis CI tests.

2021-05-26 10:12 UTC, erikmd commented on learn-ocaml.el
>                (message-box "Server changed succesfully")
@LouisAyroles don't you think these two lines should be swapped?
first, the message on server-change,
then the question(s) about tokens?

2021-05-26 10:18 UTC, LouisAyroles commented on learn-ocaml.el
>                (message-box "Server changed succesfully")
Yes you're right, but it is still a work in progress. Because, I think this isn't enough, in case where you don't have a token to provide, we have to ask user if he wants to create a new one.

2021-05-26 10:42 UTC, erikmd commented on learn-ocaml.el
>                (message-box "Server changed succesfully")
OK, so not merging yet and putting the PR in draft mode; feel free to get out of the draft mode when you'll think it's ready :)

2021-05-27 13:40 UTC, erikmd requested changes
Thanks @LouisAyroles, at first sight looks good.
But I believe you should put the line `(learn-ocaml-show-metadata)` **before** `(learn-ocaml-display-exercise-list)`. Can you amend your commit?

Also, the indentation looks weird on GitHub, certainly because you used some TABs characters instead of 8+ spaces. So can you:

1. remove this TABs (e.g., select the code of the function `learn-ocaml-change-server`; do <kbd>M-x replace-string C-q C-i RET C-u 8 SPC RET</kbd>) → here, `C-q C-i` is the standard way to write a non-printing character, here, a TAB; and `C-u 8` means "repeat 8 times the following key".
2. check that you have these lines somewhere in your `.emacs`, for automating this in your upcoming edits?
   ```elisp
   (add-hook 'prog-mode-hook #'(lambda () (unless (derived-mode-p 'makefile-mode)
                                            (setq indent-tabs-mode nil))))
   (add-hook 'sgml-mode-hook #'(lambda () (setq indent-tabs-mode nil)))
   (add-hook 'nxml-mode-hook #'(lambda () (setq indent-tabs-mode nil)))
   ```
   cf. https://github.com/erikmd/tapfa-init.el/blob/1fe972bfaa1b6e58a24765c99c0bf80ee7813660/.emacs#L132-L135

2021-05-27 14:49 UTC, erikmd approved these changes
Tested the PR successfully. Merging now.

@LouisAyroles small suggestion for your upcoming PRs: at each time you are creating (or editing an existing) function:

reindent it before committing − it's as easy as selecting this function and typing <kbd>TAB</kbd>

(as Elisp code is much more legible when opening parentheses follow the structure of the code)

2021-05-27 14:49 UTC, merged